apiVersion : apps/v1
kind: Deployment
metadata:
  name: kedasendk8s
spec:
  selector:
    matchLabels:
      app: kedasendk8s
  template:
    metadata:
      labels:
        app: kedasendk8s
    spec:
      containers:
        - name: sendk8s
          image: rcalazansn/keda-send
          env:
            - name: RABBITMQ__Hostname
              value: "192.168.0.176"
            - name: RABBITMQ__Port
              value: "5672"
            - name: RABBITMQ__UserName
              value: calazans
            - name: RABBITMQ__Password
              value: calazans

---

apiVersion: v1
kind: Service
metadata:
    name: sendk8s-service
spec:
    selector:
      app: kedasendk8s
    ports:
      - port: 80 #service port
        targetPort: 8077 #container port
    type: ClusterIP